import pytest

from common.datatypes import Entity
from newsfetch_enrichers.entity_composer import EntityComposer_AllenAI_BILOU_Strategy, EntityComposer_Transformers_BI_Strategy

def test_EntityComposer_HuggingFace_BI_Strategy_1():
    named_entities = [
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=0.9,
               pos_tag=None, start_offset=0, end_offset=3),
        Entity(entity='Horizon', label='ORG', model_label='I-ORG', description=None, confidence=0.8,
               pos_tag=None, start_offset=4, end_offset=11),
        Entity(entity='##s', label='ORG', model_label='I-ORG', description=None, confidence=0.5,
               pos_tag=None, start_offset=11, end_offset=12),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=0.9,
               pos_tag=None, start_offset=20, end_offset=27),
        Entity(entity='##Lord', label='MISC', model_label='B-MISC', description=None, confidence=0.8,
               pos_tag=None, start_offset=27, end_offset=32),
        Entity(entity='##s', label='MISC', model_label='B-MISC', description=None, confidence=0.7,
               pos_tag=None, start_offset=32, end_offset=33),
        Entity(entity='Million', label='MISC', model_label='I-MISC', description=None, confidence=0.6,
               pos_tag=None, start_offset=34, end_offset=41),
        Entity(entity='##Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.5,
               pos_tag=None, start_offset=41, end_offset=45),
        Entity(entity='##s', label='MISC', model_label='I-MISC', description=None, confidence=0.4,
               pos_tag=None, start_offset=45, end_offset=46),
        Entity(entity='France', label='LOC', model_label='B-LOC', description=None, confidence=0.999679684638977,
               pos_tag=None, start_offset=202, end_offset=208),
        Entity(entity='Million', label='ORG', model_label='I-ORG', description=None, confidence=0.7165781855583191,
               pos_tag=None, start_offset=238, end_offset=245),
        Entity(entity='Victor', label='ORG', model_label='I-ORG', description=None, confidence=0.6123574376106262,
               pos_tag=None, start_offset=246, end_offset=252),
        Entity(entity='##ies', label='ORG', model_label='I-ORG', description=None, confidence=0.8472314476966858,
               pos_tag=None, start_offset=252, end_offset=255),
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=0.9424639940261841,
               pos_tag=None, start_offset=284, end_offset=287),
        Entity(entity='Horizon', label='ORG', model_label='I-ORG', description=None, confidence=0.8908991813659668,
               pos_tag=None, start_offset=288, end_offset=295),
        Entity(entity='##s', label='ORG', model_label='I-ORG', description=None, confidence=0.39791586995124817,
               pos_tag=None, start_offset=295, end_offset=296),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=0.6918440461158752,
               pos_tag=None, start_offset=333, end_offset=340),
        Entity(entity='Lords', label='MISC', model_label='I-MISC', description=None, confidence=0.9249758720397949,
               pos_tag=None, start_offset=341, end_offset=346),
        Entity(entity='iOS', label='MISC', model_label='B-MISC', description=None, confidence=0.914954662322998,
               pos_tag=None, start_offset=366, end_offset=369),
        Entity(entity='Android', label='MISC', model_label='B-MISC', description=None, confidence=0.8116571307182312,
               pos_tag=None, start_offset=374, end_offset=381),
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=0.9972798824310303,
               pos_tag=None, start_offset=383, end_offset=386),
        Entity(entity='Horizon', label='ORG', model_label='I-ORG', description=None, confidence=0.9950056672096252,
               pos_tag=None, start_offset=387, end_offset=394),
        Entity(entity='##s', label='ORG', model_label='I-ORG', description=None, confidence=0.9101005792617798,
               pos_tag=None, start_offset=394, end_offset=395),
        Entity(entity='Expedition', label='MISC', model_label='B-MISC', description=None, confidence=0.5456990599632263,
               pos_tag=None, start_offset=498, end_offset=508),
        Entity(entity='R', label='MISC', model_label='B-MISC', description=None, confidence=0.9557915925979614,
               pos_tag=None, start_offset=575, end_offset=576),
        Entity(entity='##TS', label='MISC', model_label='I-MISC', description=None, confidence=0.6697306632995605,
               pos_tag=None, start_offset=576, end_offset=578),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=0.9091442823410034,
               pos_tag=None, start_offset=599, end_offset=606),
        Entity(entity='Lords', label='MISC', model_label='I-MISC', description=None, confidence=0.9680476188659668,
               pos_tag=None, start_offset=607, end_offset=612),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=0.8155752420425415,
               pos_tag=None, start_offset=626, end_offset=633),
        Entity(entity='Lords', label='MISC', model_label='I-MISC', description=None, confidence=0.9457178115844727,
               pos_tag=None, start_offset=634, end_offset=639),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=0.6585820317268372,
               pos_tag=None, start_offset=710, end_offset=717),
        Entity(entity='Lords', label='MISC', model_label='I-MISC', description=None, confidence=0.9308199286460876,
               pos_tag=None, start_offset=718, end_offset=723),
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=0.8665662407875061,
               pos_tag=None, start_offset=892, end_offset=895),
        Entity(entity='Horizon', label='ORG', model_label='I-ORG', description=None, confidence=0.8983034491539001,
               pos_tag=None, start_offset=896, end_offset=903),
        Entity(entity='##s', label='MISC', model_label='I-MISC', description=None, confidence=0.4995046854019165,
               pos_tag=None, start_offset=903, end_offset=904),
        Entity(entity='Million', label='ORG', model_label='B-ORG', description=None, confidence=0.6769078373908997,
               pos_tag=None, start_offset=916, end_offset=923),
        Entity(entity='Lords', label='MISC', model_label='I-MISC', description=None, confidence=0.7047460079193115,
               pos_tag=None, start_offset=924, end_offset=929),
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=0.9954184293746948,
               pos_tag=None, start_offset=1077, end_offset=1080),
        Entity(entity='Horizon', label='ORG', model_label='I-ORG', description=None, confidence=0.9956730008125305,
               pos_tag=None, start_offset=1081, end_offset=1088),
        Entity(entity='##s', label='ORG', model_label='I-ORG', description=None, confidence=0.9852555990219116,
               pos_tag=None, start_offset=1088, end_offset=1089),
        Entity(entity='Expedition', label='MISC', model_label='B-MISC', description=None, confidence=0.4177040159702301,
               pos_tag=None, start_offset=1287, end_offset=1297),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=0.7476005554199219,
               pos_tag=None, start_offset=1343, end_offset=1350),
        Entity(entity='Lords', label='MISC', model_label='I-MISC', description=None, confidence=0.9434912204742432,
               pos_tag=None, start_offset=1351, end_offset=1356),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=0.942553699016571,
               pos_tag=None, start_offset=1670, end_offset=1677),
        Entity(entity='Lords', label='MISC', model_label='I-MISC', description=None, confidence=0.9729210734367371,
               pos_tag=None, start_offset=1678, end_offset=1683),
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=0.9840704202651978,
               pos_tag=None, start_offset=1748, end_offset=1751),
        Entity(entity='Horizon', label='ORG', model_label='I-ORG', description=None, confidence=0.9809008240699768,
               pos_tag=None, start_offset=1752, end_offset=1759),
        Entity(entity='##s', label='ORG', model_label='I-ORG', description=None, confidence=0.6450534462928772,
               pos_tag=None, start_offset=1759, end_offset=1760),
        Entity(entity='Victor', label='ORG', model_label='B-ORG', description=None, confidence=0.46005991101264954,
               pos_tag=None, start_offset=1942, end_offset=1948),
        Entity(entity='iOS', label='MISC', model_label='B-MISC', description=None, confidence=0.42631128430366516,
               pos_tag=None, start_offset=2401, end_offset=2404)]

    entity_composer = EntityComposer_Transformers_BI_Strategy()
    composed_entities = entity_composer.compose(named_entities)
    assert composed_entities[0].entity == "New Horizons"
    assert composed_entities[0].label == "ORG"
    assert composed_entities[0].model_label is None
    assert composed_entities[0].start_offset == 0
    assert composed_entities[0].end_offset == 12
    assert composed_entities[0].confidence == pytest.approx(0.9)

    assert composed_entities[1].entity == "MillionLords MillionLords"
    assert composed_entities[1].label == "MISC"
    assert composed_entities[1].model_label is None
    assert composed_entities[1].start_offset == 20
    assert composed_entities[1].end_offset == 46
    assert composed_entities[1].confidence == pytest.approx(0.9)


def test_EntityComposer_HuggingFace_BI_Strategy_2():
    named_entities = [
        Entity(entity='▁New', label='ORG', model_label='I-ORG', description=None, confidence=0.8,
               pos_tag=None, start_offset=0, end_offset=3),
        Entity(entity='▁Horizon', label='ORG', model_label='I-ORG', description=None, confidence=0.7,
               pos_tag=None, start_offset=4, end_offset=11),
        Entity(entity='s', label='ORG', model_label='I-ORG', description=None, confidence=0.4,
               pos_tag=None, start_offset=11, end_offset=12),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9999388456344604,
               pos_tag=None, start_offset=20, end_offset=27),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.9999550580978394,
               pos_tag=None, start_offset=28, end_offset=32),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9998821020126343,
               pos_tag=None, start_offset=32, end_offset=33),
        Entity(entity='▁Expedi', label='MISC', model_label='I-MISC', description=None, confidence=0.9995811581611633,
               pos_tag=None, start_offset=115, end_offset=121),
        Entity(entity='tions', label='MISC', model_label='I-MISC', description=None, confidence=0.9948052763938904,
               pos_tag=None, start_offset=121, end_offset=126),
        Entity(entity='▁L', label='LOC', model_label='I-LOC', description=None, confidence=0.9999878406524658,
               pos_tag=None, start_offset=196, end_offset=197),
        Entity(entity='YON', label='LOC', model_label='I-LOC', description=None, confidence=0.9999880790710449,
               pos_tag=None, start_offset=197, end_offset=200),
        Entity(entity='▁France', label='LOC', model_label='I-LOC', description=None, confidence=0.9999964237213135,
               pos_tag=None, start_offset=202, end_offset=208),
        Entity(entity='▁Million', label='ORG', model_label='I-ORG', description=None, confidence=0.9999654293060303,
               pos_tag=None, start_offset=238, end_offset=245),
        Entity(entity='▁Victor', label='ORG', model_label='I-ORG', description=None, confidence=0.9999769926071167,
               pos_tag=None, start_offset=246, end_offset=252),
        Entity(entity='ies', label='ORG', model_label='I-ORG', description=None, confidence=0.999975323677063,
               pos_tag=None, start_offset=252, end_offset=255),
        Entity(entity='▁New', label='MISC', model_label='I-MISC', description=None, confidence=0.9998815059661865,
               pos_tag=None, start_offset=284, end_offset=287),
        Entity(entity='▁Horizon', label='MISC', model_label='I-MISC', description=None, confidence=0.999885082244873,
               pos_tag=None, start_offset=288, end_offset=295),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9998884201049805,
               pos_tag=None, start_offset=295, end_offset=296),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9998956918716431,
               pos_tag=None, start_offset=333, end_offset=340),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.9999567270278931,
               pos_tag=None, start_offset=341, end_offset=345),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9998676776885986,
               pos_tag=None, start_offset=345, end_offset=346),
        Entity(entity='▁iOS', label='MISC', model_label='I-MISC', description=None, confidence=0.5338975787162781,
               pos_tag=None, start_offset=366, end_offset=369),
        Entity(entity='▁Android', label='MISC', model_label='I-MISC', description=None, confidence=0.9465482831001282,
               pos_tag=None, start_offset=374, end_offset=381),
        Entity(entity='▁New', label='MISC', model_label='I-MISC', description=None, confidence=0.9955998659133911,
               pos_tag=None, start_offset=383, end_offset=386),
        Entity(entity='▁Horizon', label='MISC', model_label='I-MISC', description=None, confidence=0.9917435050010681,
               pos_tag=None, start_offset=387, end_offset=394),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9978440999984741,
               pos_tag=None, start_offset=394, end_offset=395),
        Entity(entity='▁Expedi', label='MISC', model_label='I-MISC', description=None, confidence=0.9993640780448914,
               pos_tag=None, start_offset=498, end_offset=504),
        Entity(entity='tions', label='MISC', model_label='I-MISC', description=None, confidence=0.9951519966125488,
               pos_tag=None, start_offset=504, end_offset=509),
        Entity(entity='▁RT', label='MISC', model_label='I-MISC', description=None, confidence=0.9990197420120239,
               pos_tag=None, start_offset=575, end_offset=577),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9999507665634155,
               pos_tag=None, start_offset=599, end_offset=606),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.9999736547470093,
               pos_tag=None, start_offset=607, end_offset=611),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9998834133148193,
               pos_tag=None, start_offset=611, end_offset=612),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9999475479125977,
               pos_tag=None, start_offset=626, end_offset=633),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.9999769926071167,
               pos_tag=None, start_offset=634, end_offset=638),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9999337196350098,
               pos_tag=None, start_offset=638, end_offset=639),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9999375343322754,
               pos_tag=None, start_offset=710, end_offset=717),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.9999713897705078,
               pos_tag=None, start_offset=718, end_offset=722),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9999152421951294,
               pos_tag=None, start_offset=722, end_offset=723),
        Entity(entity='▁New', label='MISC', model_label='I-MISC', description=None, confidence=0.9996799230575562,
               pos_tag=None, start_offset=892, end_offset=895),
        Entity(entity='▁Horizon', label='MISC', model_label='I-MISC', description=None, confidence=0.9996545314788818,
               pos_tag=None, start_offset=896, end_offset=903),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9998385906219482,
               pos_tag=None, start_offset=903, end_offset=904),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9999361038208008,
               pos_tag=None, start_offset=916, end_offset=923),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.9999715089797974,
               pos_tag=None, start_offset=924, end_offset=928),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9999158382415771,
               pos_tag=None, start_offset=928, end_offset=929),
        Entity(entity='▁New', label='ORG', model_label='I-ORG', description=None, confidence=0.9999669790267944,
               pos_tag=None, start_offset=1077, end_offset=1080),
        Entity(entity='▁Horizon', label='ORG', model_label='I-ORG', description=None, confidence=0.9999256134033203,
               pos_tag=None, start_offset=1081, end_offset=1088),
        Entity(entity='s', label='ORG', model_label='I-ORG', description=None, confidence=0.9999691247940063,
               pos_tag=None, start_offset=1088, end_offset=1089),
        Entity(entity='▁Expedi', label='MISC', model_label='I-MISC', description=None, confidence=0.9994086027145386,
               pos_tag=None, start_offset=1287, end_offset=1293),
        Entity(entity='tions', label='MISC', model_label='I-MISC', description=None, confidence=0.9967337846755981,
               pos_tag=None, start_offset=1293, end_offset=1298),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9999364614486694,
               pos_tag=None, start_offset=1343, end_offset=1350),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.9999741315841675,
               pos_tag=None, start_offset=1351, end_offset=1355),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9998608827590942,
               pos_tag=None, start_offset=1355, end_offset=1356),
        Entity(entity='▁Expedi', label='MISC', model_label='I-MISC', description=None, confidence=0.9700010418891907,
               pos_tag=None, start_offset=1358, end_offset=1364),
        Entity(entity='▁Expedi', label='MISC', model_label='I-MISC', description=None, confidence=0.9984440207481384,
               pos_tag=None, start_offset=1615, end_offset=1621),
        Entity(entity='tions', label='MISC', model_label='I-MISC', description=None, confidence=0.8355903625488281,
               pos_tag=None, start_offset=1621, end_offset=1626),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9998781681060791,
               pos_tag=None, start_offset=1670, end_offset=1677),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.999956488609314,
               pos_tag=None, start_offset=1678, end_offset=1682),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.99982750415802,
               pos_tag=None, start_offset=1682, end_offset=1683),
        Entity(entity='▁New', label='MISC', model_label='I-MISC', description=None, confidence=0.9999203681945801,
               pos_tag=None, start_offset=1748, end_offset=1751),
        Entity(entity='▁Horizon', label='MISC', model_label='I-MISC', description=None, confidence=0.9999125003814697,
               pos_tag=None, start_offset=1752, end_offset=1759),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9997797608375549,
               pos_tag=None, start_offset=1759, end_offset=1760),
        Entity(entity='▁Ben', label='PERSON', model_label='I-PER', description=None, confidence=0.9999897480010986,
               pos_tag=None, start_offset=1889, end_offset=1892),
        Entity(entity='o', label='PERSON', model_label='I-PER', description=None, confidence=0.999975323677063,
               pos_tag=None, start_offset=1892, end_offset=1893),
        Entity(entity='it', label='PERSON', model_label='I-PER', description=None, confidence=0.9999884366989136,
               pos_tag=None, start_offset=1893, end_offset=1895),
        Entity(entity='▁Du', label='PERSON', model_label='I-PER', description=None, confidence=0.9999834299087524,
               pos_tag=None, start_offset=1896, end_offset=1898),
        Entity(entity='cre', label='PERSON', model_label='I-PER', description=None, confidence=0.9999514818191528,
               pos_tag=None, start_offset=1898, end_offset=1901),
        Entity(entity='st', label='PERSON', model_label='I-PER', description=None, confidence=0.9999731779098511,
               pos_tag=None, start_offset=1901, end_offset=1903),
        Entity(entity='▁Million', label='ORG', model_label='I-ORG', description=None, confidence=0.9999611377716064,
               pos_tag=None, start_offset=1934, end_offset=1941),
        Entity(entity='▁Victor', label='ORG', model_label='I-ORG', description=None, confidence=0.999975323677063,
               pos_tag=None, start_offset=1942, end_offset=1948),
        Entity(entity='ies', label='ORG', model_label='I-ORG', description=None, confidence=0.9999688863754272,
               pos_tag=None, start_offset=1948, end_offset=1951),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9999123811721802,
               pos_tag=None, start_offset=2058, end_offset=2065),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.9999490976333618,
               pos_tag=None, start_offset=2066, end_offset=2070),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9997902512550354,
               pos_tag=None, start_offset=2070, end_offset=2071),
        Entity(entity='▁Expedi', label='MISC', model_label='I-MISC', description=None, confidence=0.9992576241493225,
               pos_tag=None, start_offset=2134, end_offset=2140),
        Entity(entity='tions', label='MISC', model_label='I-MISC', description=None, confidence=0.9785085320472717,
               pos_tag=None, start_offset=2140, end_offset=2145),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9998486042022705,
               pos_tag=None, start_offset=2166, end_offset=2173),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.9999251365661621,
               pos_tag=None, start_offset=2174, end_offset=2178),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.999646782875061,
               pos_tag=None, start_offset=2178, end_offset=2179),
        Entity(entity='▁Million', label='MISC', model_label='I-MISC', description=None, confidence=0.9999384880065918,
               pos_tag=None, start_offset=2256, end_offset=2263),
        Entity(entity='▁Lord', label='MISC', model_label='I-MISC', description=None, confidence=0.9999706745147705,
               pos_tag=None, start_offset=2264, end_offset=2268),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.9998822212219238,
               pos_tag=None, start_offset=2268, end_offset=2269),
        Entity(entity='▁New', label='MISC', model_label='I-MISC', description=None, confidence=0.9999325275421143,
               pos_tag=None, start_offset=2270, end_offset=2273),
        Entity(entity='▁Horizon', label='MISC', model_label='I-MISC', description=None, confidence=0.9999493360519409,
               pos_tag=None, start_offset=2274, end_offset=2281),
        Entity(entity='s', label='MISC', model_label='I-MISC', description=None, confidence=0.999575674533844,
               pos_tag=None, start_offset=2281, end_offset=2282)]

    entity_composer = EntityComposer_Transformers_BI_Strategy()
    composed_entities = entity_composer.compose(named_entities)
    assert composed_entities[0].entity == "New Horizons"
    assert composed_entities[0].label == "ORG"
    assert composed_entities[0].model_label is None
    assert composed_entities[0].start_offset == 0
    assert composed_entities[0].end_offset == 12
    assert composed_entities[0].confidence == pytest.approx(0.8)


def test_EntityComposer_AllenAI_BILOU_Strategy():
    named_entities = [
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Horizons', label='ORG', model_label='L-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='LYON', label='LOC', model_label='U-LOC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='France', label='LOC', model_label='U-LOC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Developer', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='I-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Victories', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='New', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Horizons', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='MMO', label='MISC', model_label='U-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Android', label='MISC', model_label='U-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Horizons', label='ORG', model_label='L-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Expeditions', label='MISC', model_label='U-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='RTS', label='MISC', model_label='U-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='New', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Horizons', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='UI', label='MISC', model_label='U-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Horizons', label='ORG', model_label='L-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Expeditions', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='–', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Expeditions', label='ORG', model_label='U-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Horizons', label='ORG', model_label='L-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Benoit', label='PERSON', model_label='B-PER', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Ducrest', label='PERSON', model_label='L-PER', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Creative', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Director', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Victories', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Expeditions', label='MISC', model_label='U-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='’re', label='ORG', model_label='U-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='ORG', model_label='B-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='ORG', model_label='I-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='New', label='ORG', model_label='I-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Horizons', label='ORG', model_label='I-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Teaser', label='ORG', model_label='L-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='New', label='ORG', model_label='B-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Horizons', label='ORG', model_label='L-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Million', label='MISC', model_label='B-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='Lords', label='MISC', model_label='L-MISC', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None),
        Entity(entity='MillionLords.com', label='ORG', model_label='U-ORG', description=None, confidence=1.0,
               pos_tag=None, start_offset=None, end_offset=None),
        Entity(entity='Twitter', label='ORG', model_label='U-ORG', description=None, confidence=1.0, pos_tag=None,
               start_offset=None, end_offset=None)]

    entity_composer = EntityComposer_AllenAI_BILOU_Strategy()
    composed_entities = entity_composer.compose(named_entities)
    assert composed_entities[0].entity == "New Horizons"
    assert composed_entities[0].label == "ORG"
    assert composed_entities[0].model_label is None
